# Generated by Django 2.1.5 on 2019-02-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=40)),
                ('college', models.CharField(max_length=60)),
                ('varsity', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=5)),
                ('religion', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='institues',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.Personal_info'),
        ),
    ]
