# Generated by Django 2.1.5 on 2019-03-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institues',
            new_name='Institutes',
        ),
    ]
