# Generated by Django 2.1.5 on 2019-04-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20190325_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=10)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.Personal_info')),
            ],
        ),
        migrations.RemoveField(
            model_name='institutes',
            name='info',
        ),
        migrations.DeleteModel(
            name='Institutes',
        ),
    ]
