# Generated by Django 2.1.5 on 2019-04-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0003_auto_20190401_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
