# Generated by Django 2.1.5 on 2019-04-03 05:03

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('intro', '0004_education_favourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_info',
            new_name='Biodata',
        ),
    ]
