# Generated by Django 2.2 on 2019-04-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('intro', '0006_auto_20190403_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Degrees',
        ),
        migrations.RenameModel(
            old_name='Biodata',
            new_name='Person',
        ),
    ]
