# Generated by Django 2.2 on 2019-06-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0008_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
